# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DLustosa/Desktop/Exemplo_vivado/CAM_OV7670_ZYBO/CAM_OV7670_ZYBO.srcs/sources_1/bd/camera_vga/ip/camera_vga_processing_system7_0_0/camera_vga_processing_system7_0_0.xci
# IP: The module: 'camera_vga_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DLustosa/Desktop/Exemplo_vivado/CAM_OV7670_ZYBO/CAM_OV7670_ZYBO.srcs/sources_1/bd/camera_vga/ip/camera_vga_processing_system7_0_0/camera_vga_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_vga_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/DLustosa/Desktop/Exemplo_vivado/CAM_OV7670_ZYBO/CAM_OV7670_ZYBO.srcs/sources_1/bd/camera_vga/ip/camera_vga_processing_system7_0_0/camera_vga_processing_system7_0_0.xci
# IP: The module: 'camera_vga_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DLustosa/Desktop/Exemplo_vivado/CAM_OV7670_ZYBO/CAM_OV7670_ZYBO.srcs/sources_1/bd/camera_vga/ip/camera_vga_processing_system7_0_0/camera_vga_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_vga_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
