# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_frame.xdc

# Block Designs: bd/captura_frame/captura_frame.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame || ORIG_REF_NAME==captura_frame} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_processing_system7_0_0/captura_frame_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_processing_system7_0_0 || ORIG_REF_NAME==captura_frame_processing_system7_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_Image_Visualization_0_0/captura_frame_Image_Visualization_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_Image_Visualization_0_0 || ORIG_REF_NAME==captura_frame_Image_Visualization_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_ov7670_controller_0_0/captura_frame_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_ov7670_controller_0_0 || ORIG_REF_NAME==captura_frame_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_comandostop_v1_0_0_0/captura_frame_comandostop_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_comandostop_v1_0_0_0 || ORIG_REF_NAME==captura_frame_comandostop_v1_0_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_debounce_0_0/captura_frame_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_debounce_0_0 || ORIG_REF_NAME==captura_frame_debounce_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_ov7670_capture_0_0/captura_frame_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_ov7670_capture_0_0 || ORIG_REF_NAME==captura_frame_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_xlconstant_0_0/captura_frame_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_xlconstant_0_0 || ORIG_REF_NAME==captura_frame_xlconstant_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_xlconstant_0_1/captura_frame_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_xlconstant_0_1 || ORIG_REF_NAME==captura_frame_xlconstant_0_1} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_xlconstant_0_2/captura_frame_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_xlconstant_0_2 || ORIG_REF_NAME==captura_frame_xlconstant_0_2} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_proc_sys_reset_0_0/captura_frame_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_proc_sys_reset_0_0 || ORIG_REF_NAME==captura_frame_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_xbar_0/captura_frame_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_xbar_0 || ORIG_REF_NAME==captura_frame_xbar_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_axi_interconnect_0_0/captura_frame_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_axi_interconnect_0_0 || ORIG_REF_NAME==captura_frame_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_rgb444_to_grayscale_0_0/captura_frame_rgb444_to_grayscale_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_rgb444_to_grayscale_0_0 || ORIG_REF_NAME==captura_frame_rgb444_to_grayscale_0_0} -quiet] -quiet

# IP: bd/captura_frame/ip/captura_frame_auto_pc_0/captura_frame_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==captura_frame_auto_pc_0 || ORIG_REF_NAME==captura_frame_auto_pc_0} -quiet] -quiet

# XDC: bd/captura_frame/captura_frame_ooc.xdc
