# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_ov7670.xdc

# Block Designs: bd/ov7670_QVGA/ov7670_QVGA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA || ORIG_REF_NAME==ov7670_QVGA} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_processing_system7_0_0/ov7670_QVGA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_processing_system7_0_0 || ORIG_REF_NAME==ov7670_QVGA_processing_system7_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_xbar_0/ov7670_QVGA_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_xbar_0 || ORIG_REF_NAME==ov7670_QVGA_xbar_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_axi_interconnect_0_0/ov7670_QVGA_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_axi_interconnect_0_0 || ORIG_REF_NAME==ov7670_QVGA_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_proc_sys_reset_0_0 || ORIG_REF_NAME==ov7670_QVGA_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_xlconstant_0_0/ov7670_QVGA_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_xlconstant_0_0 || ORIG_REF_NAME==ov7670_QVGA_xlconstant_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_xlconstant_1_0/ov7670_QVGA_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_xlconstant_1_0 || ORIG_REF_NAME==ov7670_QVGA_xlconstant_1_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_xlconstant_2_0/ov7670_QVGA_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_xlconstant_2_0 || ORIG_REF_NAME==ov7670_QVGA_xlconstant_2_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_Image_Visualization_0_0/ov7670_QVGA_Image_Visualization_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_Image_Visualization_0_0 || ORIG_REF_NAME==ov7670_QVGA_Image_Visualization_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_ov7670_controller_0_0/ov7670_QVGA_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_ov7670_controller_0_0 || ORIG_REF_NAME==ov7670_QVGA_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_comandostop_v1_0_0_0/ov7670_QVGA_comandostop_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_comandostop_v1_0_0_0 || ORIG_REF_NAME==ov7670_QVGA_comandostop_v1_0_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_debounce_0_0/ov7670_QVGA_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_debounce_0_0 || ORIG_REF_NAME==ov7670_QVGA_debounce_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_ov7670_capture_0_0/ov7670_QVGA_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_ov7670_capture_0_0 || ORIG_REF_NAME==ov7670_QVGA_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_rgb444_to_grayscale_0_0/ov7670_QVGA_rgb444_to_grayscale_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_rgb444_to_grayscale_0_0 || ORIG_REF_NAME==ov7670_QVGA_rgb444_to_grayscale_0_0} -quiet] -quiet

# IP: bd/ov7670_QVGA/ip/ov7670_QVGA_auto_pc_0/ov7670_QVGA_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ov7670_QVGA_auto_pc_0 || ORIG_REF_NAME==ov7670_QVGA_auto_pc_0} -quiet] -quiet

# XDC: bd/ov7670_QVGA/ov7670_QVGA_ooc.xdc
