# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dougl/Desktop/TESTES_CAM_ZYBO/CAPTURE_FRAME/captura_frame/captura_frame.srcs/sources_1/bd/captura_frame/ip/captura_frame_processing_system7_0_0/captura_frame_processing_system7_0_0.xci
# IP: The module: 'captura_frame_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dougl/Desktop/TESTES_CAM_ZYBO/CAPTURE_FRAME/captura_frame/captura_frame.srcs/sources_1/bd/captura_frame/ip/captura_frame_processing_system7_0_0/captura_frame_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'captura_frame_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/dougl/Desktop/TESTES_CAM_ZYBO/CAPTURE_FRAME/captura_frame/captura_frame.srcs/sources_1/bd/captura_frame/ip/captura_frame_processing_system7_0_0/captura_frame_processing_system7_0_0.xci
# IP: The module: 'captura_frame_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dougl/Desktop/TESTES_CAM_ZYBO/CAPTURE_FRAME/captura_frame/captura_frame.srcs/sources_1/bd/captura_frame/ip/captura_frame_processing_system7_0_0/captura_frame_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'captura_frame_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
