# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZYBO.xdc

# Block Designs: bd/cam_pmodtest_arthur/cam_pmodtest_arthur.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur || ORIG_REF_NAME==cam_pmodtest_arthur} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_processing_system7_0_0/cam_pmodtest_arthur_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_processing_system7_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_processing_system7_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_comandostop_v1_0_0_0/cam_pmodtest_arthur_comandostop_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_comandostop_v1_0_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_comandostop_v1_0_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_ps7_0_axi_periph_0/cam_pmodtest_arthur_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_ps7_0_axi_periph_0 || ORIG_REF_NAME==cam_pmodtest_arthur_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_rst_ps7_0_100M_0/cam_pmodtest_arthur_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_rst_ps7_0_100M_0 || ORIG_REF_NAME==cam_pmodtest_arthur_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_ov7670_controller_0_0/cam_pmodtest_arthur_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_ov7670_controller_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_Address_Generator_0_0/cam_pmodtest_arthur_Address_Generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_Address_Generator_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_Address_Generator_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_VGA_0_0/cam_pmodtest_arthur_VGA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_VGA_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_VGA_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_RGB_0_0/cam_pmodtest_arthur_RGB_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_RGB_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_RGB_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_debounce_0_0/cam_pmodtest_arthur_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_debounce_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_debounce_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_ov7670_capture_0_0/cam_pmodtest_arthur_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_ov7670_capture_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_blk_mem_gen_0_0/cam_pmodtest_arthur_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_blk_mem_gen_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_xlconstant_0_0/cam_pmodtest_arthur_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_xlconstant_0_0 || ORIG_REF_NAME==cam_pmodtest_arthur_xlconstant_0_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_xlconstant_1_0/cam_pmodtest_arthur_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_xlconstant_1_0 || ORIG_REF_NAME==cam_pmodtest_arthur_xlconstant_1_0} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_clk_wiz_0_1/cam_pmodtest_arthur_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_clk_wiz_0_1 || ORIG_REF_NAME==cam_pmodtest_arthur_clk_wiz_0_1} -quiet] -quiet

# IP: bd/cam_pmodtest_arthur/ip/cam_pmodtest_arthur_auto_pc_0/cam_pmodtest_arthur_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam_pmodtest_arthur_auto_pc_0 || ORIG_REF_NAME==cam_pmodtest_arthur_auto_pc_0} -quiet] -quiet

# XDC: bd/cam_pmodtest_arthur/cam_pmodtest_arthur_ooc.xdc
