# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/OV7670_VGA.xdc

# Block Designs: bd/camera/camera.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera || ORIG_REF_NAME==camera} -quiet] -quiet

# IP: bd/camera/ip/camera_processing_system7_0_0/camera_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_processing_system7_0_0 || ORIG_REF_NAME==camera_processing_system7_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_ov7670_controller_0_0/camera_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_ov7670_controller_0_0 || ORIG_REF_NAME==camera_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_ov7670_capture_0_0/camera_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_ov7670_capture_0_0 || ORIG_REF_NAME==camera_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_ov7670_vga_0_0/camera_ov7670_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_ov7670_vga_0_0 || ORIG_REF_NAME==camera_ov7670_vga_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_blk_mem_gen_0_0/camera_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_blk_mem_gen_0_0 || ORIG_REF_NAME==camera_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_clk_wiz_0_0/camera_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_clk_wiz_0_0 || ORIG_REF_NAME==camera_clk_wiz_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_xlconstant_0_0/camera_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_xlconstant_0_0 || ORIG_REF_NAME==camera_xlconstant_0_0} -quiet] -quiet

# IP: bd/camera/ip/camera_debounce_0_0/camera_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_debounce_0_0 || ORIG_REF_NAME==camera_debounce_0_0} -quiet] -quiet

# XDC: bd/camera/camera_ooc.xdc
