# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_master.xdc

# Block Designs: bd/camera_vga/camera_vga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga || ORIG_REF_NAME==camera_vga} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_processing_system7_0_0/camera_vga_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_processing_system7_0_0 || ORIG_REF_NAME==camera_vga_processing_system7_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_clk_wiz_0_0/camera_vga_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_clk_wiz_0_0 || ORIG_REF_NAME==camera_vga_clk_wiz_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_xlconstant_0_0/camera_vga_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_xlconstant_0_0 || ORIG_REF_NAME==camera_vga_xlconstant_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_blk_mem_gen_0_0/camera_vga_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_blk_mem_gen_0_0 || ORIG_REF_NAME==camera_vga_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_debounce_0_0/camera_vga_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_debounce_0_0 || ORIG_REF_NAME==camera_vga_debounce_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_ov7670_controller_0_0/camera_vga_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_ov7670_controller_0_0 || ORIG_REF_NAME==camera_vga_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_ov7670_capture_0_0/camera_vga_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_ov7670_capture_0_0 || ORIG_REF_NAME==camera_vga_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/camera_vga/ip/camera_vga_ov7670_vga_0_0/camera_vga_ov7670_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==camera_vga_ov7670_vga_0_0 || ORIG_REF_NAME==camera_vga_ov7670_vga_0_0} -quiet] -quiet

# XDC: bd/camera_vga/camera_vga_ooc.xdc
