# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dougl/Desktop/CarPlatooning/seguidor/TESTES_CAM_ZYBO/CAPTURE_FRAME/Captura_frame/Captura_frame.srcs/sources_1/bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0.xci
# IP: The module: 'ov7670_QVGA_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dougl/Desktop/CarPlatooning/seguidor/TESTES_CAM_ZYBO/CAPTURE_FRAME/Captura_frame/Captura_frame.srcs/sources_1/bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov7670_QVGA_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dougl/Desktop/CarPlatooning/seguidor/TESTES_CAM_ZYBO/CAPTURE_FRAME/Captura_frame/Captura_frame.srcs/sources_1/bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov7670_QVGA_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/dougl/Desktop/CarPlatooning/seguidor/TESTES_CAM_ZYBO/CAPTURE_FRAME/Captura_frame/Captura_frame.srcs/sources_1/bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0.xci
# IP: The module: 'ov7670_QVGA_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dougl/Desktop/CarPlatooning/seguidor/TESTES_CAM_ZYBO/CAPTURE_FRAME/Captura_frame/Captura_frame.srcs/sources_1/bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov7670_QVGA_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dougl/Desktop/CarPlatooning/seguidor/TESTES_CAM_ZYBO/CAPTURE_FRAME/Captura_frame/Captura_frame.srcs/sources_1/bd/ov7670_QVGA/ip/ov7670_QVGA_proc_sys_reset_0_0/ov7670_QVGA_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov7670_QVGA_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
